<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actualizar' => '',
    'Actualizar {modelClass}: ' => '',
    'Agua' => '',
    'Alicuota' => '',
    'Apellido' => '',
    'Are you sure you want to delete this item?' => '',
    'Cd Aptos' => '',
    'Cd Aptos Pk' => '',
    'Cd Conceptos' => '',
    'Cd Conceptos Pk' => '',
    'Cd Conjuntos' => '',
    'Cd Conjuntos Pk' => '',
    'Cd Edificios' => '',
    'Cd Edificios Pk' => '',
    'Cd Propietarios' => '',
    'Cd Propietarios Pk' => '',
    'Cod Conjunto' => '',
    'Cod Edificio' => '',
    'Cod Propietario' => '',
    'Cod User' => '',
    'Crear' => '',
    'Crear Operación' => '',
    'Crear Rol' => '',
    'Crear Roles' => '',
    'Crear Usuario' => '',
    'Create' => '',
    'Create Cd Aptos' => '',
    'Create Cd Conceptos' => '',
    'Create Cd Conjuntos' => '',
    'Create Cd Edificios' => '',
    'Create Cd Propietarios' => '',
    'Create Operaciones' => '',
    'Datos del {modelClass}: ' => '',
    'Delete' => '',
    'Descrip Concepto' => '',
    'Direccion' => '',
    'Direccion Cobro' => '',
    'Eliminar' => '',
    'Email' => '',
    'Email Edificio' => '',
    'Fondo Nro1' => '',
    'Fondo Nro2' => '',
    'Fondo Nro3' => '',
    'Fondo Nro4' => '',
    'Fondo Nro5' => '',
    'Fondo Nro6' => '',
    'Fondo Nro7' => '',
    'Fondo Nro8' => '',
    'Frecuencia' => '',
    'ID' => '',
    'Lista de Operaciones' => '',
    'Lista de Roles' => '',
    'Lista de Usuarios' => '',
    'Nombre' => '',
    'Nombre Concerje' => '',
    'Nombre Edificio' => '',
    'Nro Cedula' => '',
    'Nro Piso' => '',
    'Operacion ID' => '',
    'Operaciones' => '',
    'Porcentaje Nro1' => '',
    'Porcentaje Nro2' => '',
    'Quien Vive' => '',
    'Reset' => '',
    'Rol ID' => '',
    'Roles' => '',
    'Search' => '',
    'Telf Celular' => '',
    'Telf Concerje' => '',
    'Telf Local' => '',
    'Tipo' => '',
    'Update' => '',
    'Update Usr' => '',
    'Update {modelClass}: ' => '',
    'Users' => '',
    'Usuarios' => '',
    '¿Esta seguro de que quiere eliminar la Operación?' => '',
    '¿Está seguro que desea eliminar la operación?' => '',
];
