<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About Us' => '',
    'Activities' => '',
    'Agua' => '',
    'Alicuota' => '',
    'Apellido' => '',
    'Auth Key' => '',
    'Body *' => '',
    'Captcha Code' => '',
    'Cd Aptos Pk' => '',
    'Cd Conjuntos Pk' => '',
    'Cd Edificios Pk' => '',
    'Cd Propietarios Pk' => '',
    'Cod Conjunto' => '',
    'Cod Edificio' => '',
    'Cod Propietario' => '',
    'Cod User' => '',
    'Contact' => '',
    'Created At' => '',
    'Direccion' => '',
    'Dirección de Cobro' => '',
    'Dirección de Residencia' => '',
    'Email' => '',
    'Email *' => '',
    'Email Edificio' => '',
    'Email Personal' => '',
    'Enter your details to login' => '',
    'Está seguro de que los datos introducidos son correctos? Verificar antes de continuar ...' => '',
    'Fondo Nro1' => '',
    'Fondo Nro2' => '',
    'Fondo Nro3' => '',
    'Fondo Nro4' => '',
    'Fondo Nro5' => '',
    'Fondo Nro6' => '',
    'Fondo Nro7' => '',
    'Fondo Nro8' => '',
    'Home' => '',
    'How to contact us?' => '',
    'I forgot my username and / or password!' => '',
    'Id' => '',
    'It is very easy to give you all the information below, and plus we give you a contact form to interact with us.' => '',
    'Login' => '',
    'Logout' => '',
    'Name *' => '',
    'Nombre' => '',
    'Nombre Concerje' => '',
    'Nombre Edificio' => '',
    'Nro. Cedula' => '',
    'Nro. Piso' => '',
    'Password' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Porcentaje Nro1' => '',
    'Porcentaje Nro2' => '',
    'Quien Vive?' => '',
    'Register new user.' => '',
    'Remember Me' => '',
    'Rol' => '',
    'Rol Id' => '',
    'Start' => '',
    'Status' => '',
    'Subject *' => '',
    'Submit Message' => '',
    'Sure to log off?' => '',
    'Telf Concerje' => '',
    'Telf. Celular' => '',
    'Telf. Local' => '',
    'Update Usr' => '',
    'Update data' => '',
    'Updated At' => '',
    'Username' => '',
    'Using the form below ask your questions, doubts and we will respond as soon as possible.' => '',
    'Verification Code' => '',
    'Verification Code *' => '',
    'Where are you located?' => '',
    'Write us your message' => '',
    'Actualizar datos' => '@@@@',
    'Remember Me ' => '@@@@',
    'username' => '@@@@',
];
