<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actualizar' => '',
    'Actualizar {modelClass}: ' => '',
    'Are you sure you want to delete this item?' => '',
    'Cd Aptos' => '',
    'Cd Aptos Pk' => '',
    'Cd Edificios' => '',
    'Cod Edificio' => '',
    'Cod Propietario' => '',
    'Crear' => '',
    'Crear Edificio' => '',
    'Create' => '',
    'Create Cd Aptos' => '',
    'Delete' => '',
    'Eliminar' => '',
    'Facturas' => '',
    'Lista de Edificios' => '',
    'Operacion ID' => '',
    'Reset' => '',
    'Rol ID' => '',
    'Search' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Ver' => '',
    'Vista Edificio' => '',
    '¿Está seguro que desar eliminar el edificio?' => '',
    'Aprobar' => '@@@@',
    'Aprobar Pago' => '@@@@',
    'Cd Pagos' => '@@@@',
    'Crear Mensaje' => '@@@@',
    'Crear Mensajes' => '@@@@',
    'Crear Pago' => '@@@@',
    'Descargar Factura' => '@@@@',
    'Lista de Facturas' => '@@@@',
    'Lista de Mensajes' => '@@@@',
    'Lista de Pagos' => '@@@@',
    'Mensajes' => '@@@@',
    'Pagos' => '@@@@',
    'Ver Factura' => '@@@@',
    '¿Está seguro que desar eliminar el pago?' => '@@@@',
    '¿Está seguro(a) de elimanar este mensaje?' => '@@@@',
    '¿Seguro que desa aprobar el pago?' => '@@@@',
];
