<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Agua' => '',
    'Alicuota' => '',
    'Apellido' => '',
    'Cd Aptos Pk' => '',
    'Cd Conjuntos Pk' => '',
    'Cd Edificios Pk' => '',
    'Cd Propietarios Pk' => '',
    'Cod Conjunto' => '',
    'Cod Edificio' => '',
    'Cod Propietario' => '',
    'Cod User' => '',
    'Direccion' => '',
    'Dirección de Cobro' => '',
    'Dirección de Residencia' => '',
    'Email Edificio' => '',
    'Email Personal' => '',
    'Está seguro de que los datos introducidos son correctos? Verificar antes de continuar ...' => '',
    'Fondo Nro1' => '',
    'Fondo Nro2' => '',
    'Fondo Nro3' => '',
    'Fondo Nro4' => '',
    'Fondo Nro5' => '',
    'Fondo Nro6' => '',
    'Fondo Nro7' => '',
    'Fondo Nro8' => '',
    'It is very easy to give you all the information below, and plus we give you a contact form to interact with us.' => 'Es muy facil te suministramos toda la información a continuación, y ademas te brindamos un formulario de contacto para interactuar con nosotros.',
    'Nombre' => '',
    'Nombre Concerje' => '',
    'Nombre Edificio' => '',
    'Nro. Cedula' => '',
    'Nro. Piso' => '',
    'Porcentaje Nro1' => '',
    'Porcentaje Nro2' => '',
    'Quien Vive?' => '',
    'Telf Concerje' => '',
    'Telf. Celular' => '',
    'Telf. Local' => '',
    'Update Usr' => '',
    'About Us' => 'Sobre nosotros',
    'Activities' => 'Actividades',
    'Body *' => 'Cuerpo de Mensaje *',
    'Contact' => 'Contactanos',
    'Email *' => 'Correo *',
    'Home' => 'Inicio',
    'How to contact us?' => '¿Como contactarnos?',
    'Logout' => 'Salir',
    'Name *' => 'Nombre *',
    'Subject *' => 'Asunto *',
    'Submit Message' => 'Enviar Mensaje',
    'Sure to log off?' => 'Esta seguro de cerrar la sesión?',
    'Update data' => 'Actualizar datos',
    'Using the form below ask your questions, doubts and we will respond as soon as possible.' => 'Mediante el siguiente formulario haz tus preguntas, dudas y te responderemos a la brevedad posible.',
    'Verification Code *' => 'Codigo Verificación *',
    'Where are you located?' => '¿Donde estamos ubicados?',
    'Write us your message' => 'Escribenos tu mensaje',
];
